### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by shelltea** [yiyingcanfeng/maven-dependency-helper#3]
在2019.3.3中使用，一直处于loading，搜索也一直搜索不了。
![image](https://user-images.githubusercontent.com/864375/77289391-dc3d4d80-6d14-11ea-9594-ac79fff03700.png)

**Comment by ycfeng** [comment]
可能是网络的原因，因为数据都是从 [mvnrepository.com](http://mvnrepository.com/) 获取的，我这边的网络有时候访问速度也很慢。

**Comment by shelltea** [comment]
我把这个地址加到了翻墙软件的PAC中，也还是慢，直接访问也是慢，这个网站好像加了DDoS protection，有其他数据源可以换吗？
