### ISSUE TITLE
这个快捷键能否支持自定义

### ISSUE THREAD

**Issue by zxy1994** [yiyingcanfeng/maven-dependency-helper#5]
我从idea安装的了2.1版本，发现快捷键方式的方式调不出窗口；后面安装2.0版本才可以。希望插件能支持自定义快捷键，或者是有个图标，能让用户以鼠标点击的方式调用出该popup窗口

**Comment by PlexPt** [comment]
> 我从idea安装的了2.1版本，发现快捷键方式的方式调不出窗口；后面安装2.0版本才可以。希望插件能支持自定义快捷键，或者是有个图标，能让用户以鼠标点击的方式调用出该popup窗口

设置里面有
![image](https://user-images.githubusercontent.com/15922823/113257361-16b0d180-92fd-11eb-9e3b-249a01ca22b5.png)
