### ISSUE TITLE
cannot get artifact selection to work

### ISSUE THREAD

**Issue by jorgheymans** [yiyingcanfeng/maven-dependency-helper#8]
Hi,

I position the cursor in the <version> tag, then CTRL-SHIFT-D. Should the artifact id not be prepopulated like in the demo?

https://user-images.githubusercontent.com/193792/136768672-a33ec73c-e5c2-4439-9f55-7fb81044d33e.mp4

**Comment by ycfeng** [comment]
Thanks for your advice. Now you can get dependency by cursor location without artifactId selected.   
[Releases v2.3](https://github.com/yiyingcanfeng/maven-dependency-helper/releases/tag/2.3)  

![show4.gif](https://github.com/yiyingcanfeng/maven-dependency-helper/blob/master/show4.gif?raw=true)
